using System.Net;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Tavstal.MesterMC.Api.Models.Database.User;
using Tavstal.MesterMC.Api.Services.Database;

namespace Tavstal.MesterMC.Api.Controllers;

/// <summary>
/// Base controller class that provides common functionality for derived controllers.
/// </summary>
public abstract class CustomControllerBase : Controller
{
    protected readonly ILogger Logger;

    protected CustomControllerBase(ILogger logger)
    {
        Logger = logger;
    }
    
    /// <summary>
    /// Gets the user ID of the currently authenticated user.
    /// </summary>
    protected string? UserId => User.FindFirstValue(ClaimTypes.NameIdentifier);

    /// <summary>
    /// Retrieves the current user asynchronously using the provided user manager.
    /// </summary>
    /// <param name="manager">The user manager used to find the user by their ID.</param>
    /// <returns>A task that represents the asynchronous operation. The task result contains the current user.</returns>
    protected async Task<CustomUser?> GetCurrentUserAsync(CustomUserManager manager)
    {
        if (string.IsNullOrEmpty(UserId))
            return null;
        return await manager.FindByIdAsync(UserId);
    }

    /// <summary>
    /// Returns an HTTP response with the specified status code.
    /// </summary>
    /// <param name="status">The HTTP status code to return.</param>
    /// <returns>An IActionResult representing the HTTP response.</returns>
    public IActionResult ReturnResponseCode(HttpStatusCode status) => StatusCode((int)status);

    /// <summary>
    /// Returns an HTTP response with the specified status code, message, and value.
    /// </summary>
    /// <param name="status">The HTTP status code to return.</param>
    /// <param name="message">The message to include in the response.</param>
    /// <param name="value">The value to include in the response.</param>
    /// <returns>An IActionResult representing the HTTP response.</returns>
    public IActionResult ReturnResponseCode(HttpStatusCode status, string message, object value) => StatusCode(
        (int)status, JObject.FromObject(new { Message = message, Value = value }).ToString(Formatting.None));

    /// <summary>
    /// Returns an HTTP response with the specified status code and message.
    /// </summary>
    /// <param name="status">The HTTP status code to return.</param>
    /// <param name="message">The message to include in the response.</param>
    /// <returns>An IActionResult representing the HTTP response.</returns>
    public IActionResult ReturnResponseCode(HttpStatusCode status, string message) => StatusCode((int)status, message);

    /// <summary>
    /// Returns a JSON response with the specified JSON string.
    /// </summary>
    /// <param name="json">The JSON string to include in the response.</param>
    /// <returns>An IActionResult representing the JSON response.</returns>
    public IActionResult ReturnJson(string json) => Content(json, "application/json");

    /// <summary>
    /// Returns a JSON response with the specified object serialized to JSON.
    /// </summary>
    /// <param name="json">The object to serialize and include in the response.</param>
    /// <returns>An IActionResult representing the JSON response.</returns>
    public IActionResult ReturnJson(object json) =>
        Content(JsonConvert.SerializeObject(json, Formatting.None), "application/json");

    /// <summary>
    /// Returns a JSON response with the specified JObject.
    /// </summary>
    /// <param name="json">The JObject to include in the response.</param>
    /// <returns>An IActionResult representing the JSON response.</returns>
    public IActionResult ReturnJson(JObject json) => Content(json.ToString(Formatting.None), "application/json");

    /// <summary>
    /// Returns a JSON response with the specified JArray.
    /// </summary>
    /// <param name="json">The JArray to include in the response.</param>
    /// <returns>An IActionResult representing the JSON response.</returns>
    public IActionResult ReturnJson(JArray json) => Content(json.ToString(Formatting.None), "application/json");

    /// <summary>
    /// Redirects to an error page with the specified status code and message.
    /// </summary>
    /// <param name="status">The HTTP status code to include in the redirect.</param>
    /// <param name="message">The error message to include in the redirect.</param>
    /// <returns>An IActionResult representing the redirect response.</returns>
    public IActionResult RedirectError(HttpStatusCode status, string message) =>
        Redirect($"/oops?id={(int)status}&message={message}");
    
    /// <summary>
    /// Computes a stable ETag (Entity Tag) for the given JSON string.
    /// The ETag is generated by computing the SHA1 hash of the JSON string
    /// and encoding it in Base64 format, enclosed in double quotes.
    /// </summary>
    /// <param name="json">The JSON string for which the ETag is to be computed.</param>
    /// <returns>A string representing the computed ETag.</returns>
    protected static string ComputeETag(string json)
    {
        using var sha1 = SHA1.Create();
        var bytes = Encoding.UTF8.GetBytes(json);
        var hash = sha1.ComputeHash(bytes);
        return "\"" + Convert.ToBase64String(hash) + "\"";
    }
}